version: '3'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  api:
    container_name: api
    build: .
    ports:
      - "4000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}
